import { Injectable } from "@angular/core";

@Injectable({
    providedIn: 'root'
})
export class CountriesService {
    public countries: {name: string, abbr: string}[] = [
        { name: 'Afghanistan', abbr: 'AF' },
        { name: 'Albania', abbr: 'AL' },
        { name: 'Algeria', abbr: 'DZ' },
        { name: 'Andorra', abbr: 'AD' },
        { name: 'Angola', abbr: 'AO' },
        { name: 'Antigua and Barbuda', abbr: 'AG' },
        { name: 'Argentina', abbr: 'AR' },
        { name: 'Armenia', abbr: 'AM' },
        { name: 'Australia', abbr: 'AU' },
        { name: 'Austria', abbr: 'AT' },
        { name: 'Azerbaijan', abbr: 'AZ' },
        { name: 'Bahamas', abbr: 'BS' },
        { name: 'Bahrain', abbr: 'BH' },
        { name: 'Bangladesh', abbr: 'BD' },
        { name: 'Barbados', abbr: 'BB' },
        { name: 'Belarus', abbr: 'BY' },
        { name: 'Belgium', abbr: 'BE' },
        { name: 'Belize', abbr: 'BZ' },
        { name: 'Benin', abbr: 'BJ' },
        { name: 'Bhutan', abbr: 'BT' },
        { name: 'Bolivia', abbr: 'BO' },
        { name: 'Bosnia and Herzegovina', abbr: 'BA' },
        { name: 'Botswana', abbr: 'BW' },
        { name: 'Brazil', abbr: 'BR' },
        { name: 'Brunei', abbr: 'BN' },
        { name: 'Bulgaria', abbr: 'BG' },
        { name: 'Burkina Faso', abbr: 'BF' },
        { name: 'Burundi', abbr: 'BI' },
        { name: 'Cabo Verde', abbr: 'CV' },
        { name: 'Cambodia', abbr: 'KH' },
        { name: 'Cameroon', abbr: 'CM' },
        { name: 'Canada', abbr: 'CA' },
        { name: 'Central African Republic', abbr: 'CF' },
        { name: 'Chad', abbr: 'TD' },
        { name: 'Chile', abbr: 'CL' },
        { name: 'China', abbr: 'CN' },
        { name: 'Colombia', abbr: 'CO' },
        { name: 'Comoros', abbr: 'KM' },
        { name: 'Congo, Democratic Republic of the', abbr: 'CD' },
        { name: 'Congo, Republic of the', abbr: 'CG' },
        { name: 'Costa Rica', abbr: 'CR' },
        { name: 'Croatia', abbr: 'HR' },
        { name: 'Cuba', abbr: 'CU' },
        { name: 'Cyprus', abbr: 'CY' },
        { name: 'Czech Republic', abbr: 'CZ' },
        { name: 'Denmark', abbr: 'DK' },
        { name: 'Djibouti', abbr: 'DJ' },
        { name: 'Dominica', abbr: 'DM' },
        { name: 'Dominican Republic', abbr: 'DO' },
        { name: 'Ecuador', abbr: 'EC' },
        { name: 'Egypt', abbr: 'EG' },
        { name: 'El Salvador', abbr: 'SV' },
        { name: 'Equatorial Guinea', abbr: 'GQ' },
        { name: 'Eritrea', abbr: 'ER' },
        { name: 'Estonia', abbr: 'EE' },
        { name: 'Eswatini', abbr: 'SZ' },
        { name: 'Ethiopia', abbr: 'ET' },
        { name: 'Fiji', abbr: 'FJ' },
        { name: 'Finland', abbr: 'FI' },
        { name: 'France', abbr: 'FR' },
        { name: 'Gabon', abbr: 'GA' },
        { name: 'Gambia', abbr: 'GM' },
        { name: 'Georgia', abbr: 'GE' },
        { name: 'Germany', abbr: 'DE' },
        { name: 'Ghana', abbr: 'GH' },
        { name: 'Greece', abbr: 'GR' },
        { name: 'Grenada', abbr: 'GD' },
        { name: 'Guatemala', abbr: 'GT' },
        { name: 'Guinea', abbr: 'GN' },
        { name: 'Guinea-Bissau', abbr: 'GW' },
        { name: 'Guyana', abbr: 'GY' },
        { name: 'Haiti', abbr: 'HT' },
        { name: 'Honduras', abbr: 'HN' },
        { name: 'Hungary', abbr: 'HU' },
        { name: 'Iceland', abbr: 'IS' },
        { name: 'India', abbr: 'IN' },
        { name: 'Indonesia', abbr: 'ID' },
        { name: 'Iran', abbr: 'IR' },
        { name: 'Iraq', abbr: 'IQ' },
        { name: 'Ireland', abbr: 'IE' },
        { name: 'Israel', abbr: 'IL' },
        { name: 'Italy', abbr: 'IT' },
        { name: 'Jamaica', abbr: 'JM' },
        { name: 'Japan', abbr: 'JP' },
        { name: 'Jordan', abbr: 'JO' },
        { name: 'Kazakhstan', abbr: 'KZ' },
        { name: 'Kenya', abbr: 'KE' },
        { name: 'Kiribati', abbr: 'KI' },
        { name: 'Korea, North', abbr: 'KP' },
        { name: 'Korea, South', abbr: 'KR' },
        { name: 'Kuwait', abbr: 'KW' },
        { name: 'Kyrgyzstan', abbr: 'KG' },
        { name: 'Laos', abbr: 'LA' },
        { name: 'Latvia', abbr: 'LV' },
        { name: 'Lebanon', abbr: 'LB' },
        { name: 'Lesotho', abbr: 'LS' },
        { name: 'Liberia', abbr: 'LR' },
        { name: 'Libya', abbr: 'LY' },
        { name: 'Liechtenstein', abbr: 'LI' },
        { name: 'Lithuania', abbr: 'LT' },
        { name: 'Luxembourg', abbr: 'LU' },
        { name: 'Madagascar', abbr: 'MG' },
        { name: 'Malawi', abbr: 'MW' },
        { name: 'Malaysia', abbr: 'MY' },
        { name: 'Maldives', abbr: 'MV' },
        { name: 'Mali', abbr: 'ML' },
        { name: 'Malta', abbr: 'MT' },
        { name: 'Marshall Islands', abbr: 'MH' },
        { name: 'Mauritania', abbr: 'MR' },
        { name: 'Mauritius', abbr: 'MU' },
        { name: 'Mexico', abbr: 'MX' },
        { name: 'Micronesia', abbr: 'FM' },
        { name: 'Moldova', abbr: 'MD' },
        { name: 'Monaco', abbr: 'MC' },
        { name: 'Mongolia', abbr: 'MN' },
        { name: 'Montenegro', abbr: 'ME' },
        { name: 'Morocco', abbr: 'MA' },
        { name: 'Mozambique', abbr: 'MZ' },
        { name: 'Myanmar', abbr: 'MM' },
        { name: 'Namibia', abbr: 'NA' },
        { name: 'Nauru', abbr: 'NR' },
        { name: 'Nepal', abbr: 'NP' },
        { name: 'Netherlands', abbr: 'NL' },
        { name: 'New Zealand', abbr: 'NZ' },
        { name: 'Nicaragua', abbr: 'NI' },
        { name: 'Niger', abbr: 'NE' },
        { name: 'Nigeria', abbr: 'NG' },
        { name: 'North Macedonia', abbr: 'MK' },
        { name: 'Norway', abbr: 'NO' },
        { name: 'Oman', abbr: 'OM' },
        { name: 'Pakistan', abbr: 'PK' },
        { name: 'Palau', abbr: 'PW' },
        { name: 'Panama', abbr: 'PA' },
        { name: 'Papua New Guinea', abbr: 'PG' },
        { name: 'Paraguay', abbr: 'PY' },
        { name: 'Peru', abbr: 'PE' },
        { name: 'Philippines', abbr: 'PH' },
        { name: 'Poland', abbr: 'PL' },
        { name: 'Portugal', abbr: 'PT' },
        { name: 'Qatar', abbr: 'QA' },
        { name: 'Romania', abbr: 'RO' },
        { name: 'Russia', abbr: 'RU' },
        { name: 'Rwanda', abbr: 'RW' },
        { name: 'Saint Kitts and Nevis', abbr: 'KN' },
        { name: 'Saint Lucia', abbr: 'LC' },
        { name: 'Saint Vincent and the Grenadines', abbr: 'VC' },
        { name: 'Samoa', abbr: 'WS' },
        { name: 'San Marino', abbr: 'SM' },
        { name: 'Sao Tome and Principe', abbr: 'ST' },
        { name: 'Saudi Arabia', abbr: 'SA' },
        { name: 'Senegal', abbr: 'SN' },
        { name: 'Serbia', abbr: 'RS' },
        { name: 'Seychelles', abbr: 'SC' },
        { name: 'Sierra Leone', abbr: 'SL' },
        { name: 'Singapore', abbr: 'SG' },
        { name: 'Slovakia', abbr: 'SK' },
        { name: 'Slovenia', abbr: 'SI' },
        { name: 'Solomon Islands', abbr: 'SB' },
        { name: 'Somalia', abbr: 'SO' },
        { name: 'South Africa', abbr: 'ZA' },
        { name: 'South Sudan', abbr: 'SS' },
        { name: 'Spain', abbr: 'ES' },
        { name: 'Sri Lanka', abbr: 'LK' },
        { name: 'Sudan', abbr: 'SD' },
        { name: 'Suriname', abbr: 'SR' },
        { name: 'Sweden', abbr: 'SE' },
        { name: 'Switzerland', abbr: 'CH' },
        { name: 'Syria', abbr: 'SY' },
        { name: 'Taiwan', abbr: 'TW' },
        { name: 'Tajikistan', abbr: 'TJ' },
        { name: 'Tanzania', abbr: 'TZ' },
        { name: 'Thailand', abbr: 'TH' },
        { name: 'Timor-Leste', abbr: 'TL' },
        { name: 'Togo', abbr: 'TG' },
        { name: 'Tonga', abbr: 'TO' },
        { name: 'Trinidad and Tobago', abbr: 'TT' },
        { name: 'Tunisia', abbr: 'TN' },
        { name: 'Turkey', abbr: 'TR' },
        { name: 'Turkmenistan', abbr: 'TM' },
        { name: 'Tuvalu', abbr: 'TV' },
        { name: 'Uganda', abbr: 'UG' },
        { name: 'Ukraine', abbr: 'UA' },
        { name: 'United Arab Emirates', abbr: 'AE' },
        { name: 'United Kingdom', abbr: 'GB' },
        { name: 'United States', abbr: 'US' },
        { name: 'Uruguay', abbr: 'UY' },
        { name: 'Uzbekistan', abbr: 'UZ' },
        { name: 'Vanuatu', abbr: 'VU' },
        { name: 'Vatican City', abbr: 'VA' },
        { name: 'Venezuela', abbr: 'VE' },
        { name: 'Vietnam', abbr: 'VN' },
        { name: 'Yemen', abbr: 'YE' },
        { name: 'Zambia', abbr: 'ZM' },
        { name: 'Zimbabwe', abbr: 'ZW' }
    ];

    constructor() { }
}